name: 'Auto Translate'

on:
  workflow_dispatch: # 수동 실행
  schedule:
    - cron: '0 0 * * *' # 매일 00:00

env:
  REPOSITORY: github.repository
  GITHUB_USER: github.actor

jobs:
  auto-translate:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Translate
        uses: puleugo/kablog@main
        with:
          GH_REPOSITORY: 'puleugo.dev'
          GH_USER: 'puleugo'
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}

          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MEDIUM_TOKEN: ${{ secrets.MEDIUM_TOKEN }}
          METHOD: | 
            - READ
            - PUBLISH
